@TM:1386317010
@N:  :"":0:0:0:-1|Running in 32-bit mode
@TM:1386317017
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1386317010
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\proasic3.vhd":1782:10:1782:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\proasic3.vhd":2722:10:2722:12|M
@N: CD720 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\vhd\std.vhd":123:18:123:21|M
@N:  :"E:\workspaces\activehdl\01_dip_switch_actel\component\work\simple_dip_switch\simple_dip_switch.vhd":8:7:8:23|M
@N: CD630 :"E:\workspaces\activehdl\01_dip_switch_actel\component\work\simple_dip_switch\simple_dip_switch.vhd":8:7:8:23|M
